apiVersion: v1
kind: Pod 
metadata:
  name: mypod 
  labels:
    app: myapp
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
          matchExpressions:
        - key: type
          operator: In
          values:
          - frontend
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
      - containerPort: 80
