apiVersion: v1
kind: Pod 
metadata:
  name: mypod 
  labels:
    app: myapp
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - backend
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
      - containerPort: 80
