apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs 
  labels:
    app: rs
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        