apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache-Deployment
  labels:
    app: apache
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
       labels:
         app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd:latest
        ports:
          - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
             cpu: "200m"
             memory: "128Mi"