apiVersion: v1
kind: Service
metadata:
  name: apache-svc 
  labels:
    app: apache
  namespace: apache
spec:
  type: ClusterIp
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80